#include-once

#include "Settings.au3"
#include "Utils.au3"
#include "EU.au3"
#include "NA.au3"

Global $SpeedMod = 1

Func Dungeon_AnotherSlingshot()
	Send($MoveLeftDown)
	Sleep(16/$SettingHostTimeScaleUse*$SpeedMod)
	Send($MoveForwardDown)
	Sleep(2399/$SettingHostTimeScaleUse*$SpeedMod)
	Send($MoveLeftUp)
	Sleep(1153/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1984/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(879/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(449/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(880/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(3119/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2128/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(4224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_DecisiveBattle($time = 15000)
	_Send($MoveForwardDown)
	Sleep($time/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_KoboldChief()
	_Send($MoveForwardDown)
	_Send($MoveLeftDown)
	Sleep(447/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(2305/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2880/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(911/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(545/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(639/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(369/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(1136/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(288/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1615/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1425/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
EndFunc

Func Dungeon_DeadEndStreet()
	_Send($MoveForwardDown)
	Sleep(5500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_BeingFromTheOtherWorld()
	_Send($MoveForwardDown)
	Sleep(3000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_RegretsTooLate()
	_Send($MoveForwardDown)
	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_SnowmanAlert()
	If ($SettingUseEU == 0) Then
		DungeonNA_SnowmanAlert()
	Else
		DungeonEU_SnowmanAlert()
	EndIf
EndFunc

Func DungeonNA_SnowmanAlert()
	_Send($MoveForwardDown)
	_Send($MoveRightDown)
	Sleep(1000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(4500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	_Send($MoveRightDown)
	Sleep(2000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(2000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(6500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	_Send($MoveBackwardDown)
	Sleep(2500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	_Send($MoveRightDown)
	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_RuinsOfSanctityA()
	If $SettingUseEU == 0 Then
		DungeonNA_RuinsOfSanctityA()
	Else
		DungeonEU_RuinsOfSanctityA()
	EndIf
EndFunc

Func DungeonNA_RuinsOfSanctityA()
	_Send($MoveForwardDown)
	Sleep(4816/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2046/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(3424/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(4128/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(160/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1840/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1024/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2288/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2064/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(3136/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(880/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1056/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(3424/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(3296/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(688/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1456/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(48/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(896/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1632/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1808/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(704/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(3312/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(48/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(5488/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1744/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2304/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(64/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_RuinsOfSanctityB()
	_Send($MoveForwardDown)
	Sleep(2414/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1265/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1567/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(959/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_CadetsChallenge()
	_Send($MoveForwardDown)
	Sleep(896/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1568/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1487/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1904/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(3104/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(2671/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(3984/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2064/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1648/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
;	_Send($MoveForwardDown)
;	Sleep(3000/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
;	SpamSkill(1, 0)
;	_Send($MoveRightDown)
;	Sleep(4000/$SettingHostTimeScaleUse*$SpeedMod)
;	_Send($MoveRightUp)
;	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
;	_Send($MoveForwardUp)
;	_Send($MoveRightDown)
;	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
;	_Send($MoveForwardDown)
;	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
;	_Send($MoveForwardUp)
;	Sleep(3750/$SettingHostTimeScaleUse*$SpeedMod)
;	_Send($MoveRightUp)
EndFunc

Func Dungeon_PrairieGnollB()
	_Send($MoveForwardDown)
	_Send($MoveLeftDown)
	Sleep(2750/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(10000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(250/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(2500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_BuriedSorrow($time = 15000)
	_Send($MoveForwardDown)
	_Send($MoveRightDown)
	Sleep(900/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep($time/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_Madness()
	_Send($MoveForwardDown)
	Sleep(2063/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(4272/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(5024/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_Contact()
	_Send($MoveForwardDown)
	_Send($MoveRightDown)
	Sleep(2750/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(2000/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(4000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	_Send($MoveRightDown)
	Sleep(500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(4000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_RocktunesCabin()
	_Send($MoveForwardDown)
	_Send($MoveRightDown)
	Sleep(1200/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(6500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($BindTenticle)
	Sleep(1250/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($BindTenticle)
	Sleep(6000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(4000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($BindTenticle)
	Sleep(2000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($BindTenticle)
	_Send($MoveRightDown)
	Sleep(8000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	_Send($MoveForwardUp)
	_Send($BindTenticle)
	SpamSkill(5, 1250/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(5500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(8000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	_Send($MoveForwardDown)
	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
 	_Send($MoveForwardUp)
EndFunc

Func Dungeon_Chicanery()
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(880 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(1679 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(800 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1744 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2064 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(8303 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(256 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(3344 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1552 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(96 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1456 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1584 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(911 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1680 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1056 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1344 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1824 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(976 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(1056 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(736 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(464 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(848 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(2640 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(655 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(689 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(4735 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(1616 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(64 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1567 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1521 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(831 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(384 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(544 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1935 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(785 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(464 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(591 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(768 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(336 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(768 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(128 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1136 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(224 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(480 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(80 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1104 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(3391 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
EndFunc

Func Dungeon_RevivedFear()
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(1200/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1168/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(112/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1296/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1120/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1472/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(880/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_WestHilderForest()
	_Send($MoveForwardDown)
	Sleep(6000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	SpamSkill(1, 0)
	_Send($MoveLeftDown)
	Sleep(5000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_ForestRuinsB()
	_Send($MoveForwardDown)
	Sleep(4500/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	_Send($MoveRightDown)
	Sleep(3000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_Ambush()
	_Send($MoveForwardDown)
	Sleep(2528 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(976 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(1248 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(6064 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(799 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(689 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1824 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1088 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1087 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(864 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1120 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(272 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2672 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1616 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(111 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1873 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(143 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1169 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1568 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(176 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1839 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1024 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(288 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2960 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(736 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(3376 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(704 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_FomorianEmblem()
	If $SettingUseEU Then
		DungeonEU_FomorianEmblem()
	Else
		DungeonNA_FomorianEmblem()
	EndIf
EndFunc

Func DungeonNA_FomorianEmblem()
	_Send($MoveForwardDown)
	Sleep(8672 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(832 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(112 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(720 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1567 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1584 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(992 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(832 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(112 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(4896 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(944 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1487 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(337 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(1040 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(31 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(976 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(960 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(688 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(416 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1264 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1552 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(768 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(32 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(640 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(688 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(144 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(544 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1584 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1424 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(64 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(607 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(960 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(176 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(960 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1904 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(48 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(1840 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(80 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(3040 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(47 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(3584 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1392 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(960 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(48 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(288 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1472 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1551 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1425 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1680 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1456 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1439 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1568 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(720 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(608 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(5712 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1488 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1376 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1455 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1424 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(368 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(32 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(432 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1840 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1504 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1552 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_RedRuins()
	_Send($MoveForwardDown)
	Sleep(4336 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1536 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1600 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1552 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(3855 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1312 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2688 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1648 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1376 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(64 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(608 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(48 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(720 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(32 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(783 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(16 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(913 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1024 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1008 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(48 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(816 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(687 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(256 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(2672 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1600 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1840 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1280 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(16 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(671 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1777 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(799 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
EndFunc

Func Dungeon_MercenaryTrainingSite()
	_Send($MoveForwardDown)
	Sleep(7983 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2768 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2128 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(2560 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(991 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1313 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1424 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(4799 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(496 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(752 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(416 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1040 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(543 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1585 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(6271 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(2528 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(4623 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1697 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1903 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1167 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1728 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1872 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(672 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(4608 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(336 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(863 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(112 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(432 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(79 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(3839 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(48 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(736 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(736 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(768 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(368 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(368 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1648 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(4064 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(3791 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(3056 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(128 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(3311 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(705 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($BindNormal)
	Sleep(736 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2048 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($BindSmall)
	Sleep(1279 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(272 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(880 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1232 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(208 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(768 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(576 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(192 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(64 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(112 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(128 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(384 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(80 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(1024 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(127 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(560 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(272 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(321 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1423 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(128 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(833 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(63 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(529 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1583 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1232 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1535 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(113 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(400 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(624 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(496 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(448 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(496 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1855 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(1408 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(320 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(3856 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(144 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(6639 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2464 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(11200 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_StrongDrink()
	_Send($MoveForwardDown)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1936/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(768/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(64/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_TakingInitiative()
	_Send($MoveForwardDown)
	Sleep(1408/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(720/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(896/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(10623/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(3712/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1488/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(272/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1343/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_WhatTheDeadLeaveBehindB()
	_Send($MoveForwardDown)
	Sleep(2384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(576/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(2336/$SettingHostTimeScaleUse*$SpeedMod)
	Nuke()
	SpamSkill(1, 0)
	Sleep(1728/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1664/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2047/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(4528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(48/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(8943/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_PursuitB()
	_Send($MoveForwardDown)
	Sleep(17/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(3471/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2144/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1776/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(944/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(6607/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(3104/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2096/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2159/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_TheInvestigationA()
	_Send($MoveForwardDown)
	_Send($MoveLeftDown)
	Sleep(3263 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1452 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1250 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2128 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2063 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1441 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(832 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(5471 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(3904 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(816 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1248 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(784 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1952 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1520 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(639 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1008 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(480 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1712 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(736 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(912 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(624 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(528 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(144 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(16 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(352 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1328 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightDown)
	Sleep(1072 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardDown)
	Sleep(2064 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveRightUp)
	Sleep(6751 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(384 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(2752 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(624 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1647 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftDown)
	Sleep(4016 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1200 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2800 / $SettingHostTimeScaleUse * $SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_TheInvestigationB()
	_Send($MoveForwardDown)
	Sleep(3920/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1296/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1759/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1408/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(7168/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1695/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1856/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2288/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2112/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1120/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_TheFleeingGnollKingA()
	_Send($MoveForwardDown)
	Sleep(2272/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(752/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(3856/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(3567/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(2000/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(3904/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1472/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1407/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1904/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1184/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	_Send($MoveBackwardDown)
	Sleep(1360/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	_Send($MoveBackwardUp)
	Sleep(480/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1423/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(4768/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	_Send($MoveBackwardDown)
	Sleep(3056/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(5359/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(2863/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1088/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(2288/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(3008/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(672/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1824/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1455/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2192/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(10079/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1184/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1199/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1281/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(6624/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(960/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1711/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1632/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_HoarfrostHollow()
	If $SettingUseEU == 0 Then
		DungeonNA_HoarfrostHollow()
	Else
		DungeonEU_HoarfrostHollow()
	EndIf
EndFunc

Func DungeonNA_HoarfrostHollow()
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(911/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1841/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(175/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(945/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1311/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(688/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(1664/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1776/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(272/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(64/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(2878/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1169/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(2063/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(560/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(672/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1056/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1184/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(895/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(657/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(720/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2160/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1775/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1728/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1519/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1457/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(816/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
EndFunc

Func Dungeon_HabitatForWildPlants()
	_Send($MoveForwardDown)
	Sleep(2097/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1824/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(624/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2896/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(351/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(880/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(272/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1072/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(960/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	_Send($MoveForwardDown)
	Sleep(447/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(97/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2127/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(49/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(31/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(689/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(80/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(80/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(111/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(2161/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(64/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1536/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1696/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1472/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(447/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1329/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
EndFunc

Func Dungeon_GiveABeggarACoinA()
	_Send($MoveForwardDown)
	_Send($MoveLeftDown)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(3167/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(431/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(480/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(3296/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2160/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1504/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(5255/$SettingHostTimeScaleUse*$SpeedMod)
EndFunc

Func Dungeon_AnotherStoreroomB()
	_Send($MoveForwardDown)
	Sleep(6126/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1441/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1872/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(2287/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(688/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(4880/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1168/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(944/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(784/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
EndFunc

Func Dungeon_BeginningOfTheMemory()
	If $SettingUseEU == 0 Then
		DungeonNA_BeginningOfTheMemory()
	Else
		DungeonEU_BeginningOfTheMemory()
	EndIf
EndFunc

Func DungeonNA_BeginningOfTheMemory()
	_Send($MoveForwardDown)
	Sleep(4607/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1297/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1520/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1168/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1039/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(880/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(512/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1520/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(10127/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	_Send($MoveRightDown)
	Sleep(7328/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(191/$SettingHostTimeScaleUse)
	_Send($BindNormal)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1375/$SettingHostTimeScaleUse)
	_Send($BindSmall)
	Sleep(1664/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(720/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1952/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1552/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1039/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(897/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1776/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(704/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1535/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1616/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1600/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(432/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(3456/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($BindNormal)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1600/$SettingHostTimeScaleUse)
	_Send($BindSmall)
	Sleep(671/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(577/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1136/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(655/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(480/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1936/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(4128/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1440/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(384/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1168/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(512/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1664/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(848/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
EndFunc

Func Dungeon_FrostStones()
	If $SettingUseEU == 0 Then
		DungeonNA_FrostStones()
	Else
		DungeonEU_FrostStones()
	EndIf
EndFunc

Func Dungeon_GoldLeather()
	If $SettingUseEU == 0 Then
		DungeonNA_GoldLeather()
	Else
		DungeonEU_GoldLeather()
	EndIf
EndFunc

Func Dungeon_WindThroughTheRuins()
	If $SettingUseEU == 0 Then
		DungeonNA_WindThroughTheRuins()
	Else
		DungeonEU_WindThroughTheRuins()
	EndIf
EndFunc

Func Dungeon_ATownEngulfed()
	If $SettingUseEU == 0 Then
		DungeonNA_ATownEngulfed()
	Else
		DungeonEU_ATownEngulfed()
	EndIf
EndFunc

Func Dungeon_HellBeyondTheDoor()
	If $SettingUseEU == 0 Then
		DungeonNA_HellBeyondTheDoor()
	Else
		DungeonEU_HellBeyondTheDoor()
	EndIf
EndFunc

Func Dungeon_FriendOrFoe()
	If $SettingUseEU == 0 Then
		DungeonNA_FriendOrFoe()
	Else
		DungeonNA_FriendOrFoe() ;needs to be changed
	EndIf
EndFunc

Func Dungeon_EllissTrust()
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(1232/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(3488/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(16/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(288/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(1120/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1328/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(816/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(576/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(240/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(704/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1216/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1951/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
EndFunc

Func Dungeon_BloodPrince()
	_Send($MoveForwardDown)
	Sleep(1728/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1216/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1120/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1120/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1136/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1136/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1648/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(16/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(672/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(928/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(5376/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(704/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(3344/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(160/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(768/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(64/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(784/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(592/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(784/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(112/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(560/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(160/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1072/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(576/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(272/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(688/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(1680/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(1232/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(832/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1600/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1232/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(624/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(768/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(400/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(2144/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(848/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1008/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1088/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(944/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1136/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(928/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(736/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(624/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(992/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(2144/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(624/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1088/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1072/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(400/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1888/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(80/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(112/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1712/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(16/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1584/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(640/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(560/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(880/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(816/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(704/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(720/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(816/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1040/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(960/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(272/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(112/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(992/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(704/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(80/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(272/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(768/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(608/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1360/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1168/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1072/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(2288/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(464/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1216/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(432/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(640/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(864/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1760/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1632/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1424/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1200/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1088/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(560/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1311/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1584/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(480/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(928/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(112/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(688/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1808/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	_Send($MoveLeftUp)
	Sleep(160/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1216/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(800/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(943/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(193/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(1712/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(672/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(544/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(752/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1104/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1728/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(288/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1520/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(240/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(624/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(752/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(736/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(576/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1680/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(768/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1216/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(944/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(992/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(896/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(1136/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(368/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(352/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(928/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(704/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(576/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardDown)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(64/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(32/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveForwardUp)
	Sleep(1216/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse*$SpeedMod)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(784/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(2304/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(256/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(2320/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1664/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(784/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1152/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(448/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1856/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(640/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(576/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(224/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(1104/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(480/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(400/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(208/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(1712/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
	Sleep(656/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardDown)
	Sleep(640/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftDown)
	Sleep(80/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveLeftUp)
	Sleep(1072/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(512/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(128/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(336/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(96/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(496/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(80/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1280/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(528/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(416/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(160/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(752/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(144/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1024/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(160/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1616/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(192/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(1504/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightDown)
	Sleep(384/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveRightUp)
	Sleep(176/$SettingHostTimeScaleUse*$SpeedMod)
	_Send($MoveBackwardUp)
EndFunc
