#include-once

#include "FastPixel.au3"
#include "Settings.au3"

Global $EURunSpeedModifier = 1.2
Global $XEMode = False

Global $EU_PosY_ReturnToTown_6Party = 580
Global $EU_PosY_ReturnToTown_8Party = 580

Func DetectEU($x, $y)
	If WinExists("[Class:Valve001; Title:Vindictus EU]") Then
		$SettingUseEU = 1
	EndIf
	;If (PixelGetColor($x, $y) >= 0x4D2426) And (PixelGetColor($x, $y) <= 0x633031) Then
	;	$SettingUseEU = 1
	;EndIf
EndFunc

Func DungeonEU_FomorianEmblem()
	_Send($MoveForwardDown)
	Sleep(1936/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2335/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1569/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1824/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1472/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(544/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	_Send($MoveLeftDown)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1744/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1600/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1856/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1568/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(560/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(880/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(351/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(577/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(608/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(864/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1264/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(639/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1041/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(592/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(880/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(416/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1184/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(256/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2016/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(672/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(752/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(528/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(800/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(703/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1409/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(608/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1696/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1871/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1553/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(480/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1648/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1232/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(416/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(800/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1936/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(464/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1184/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1888/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1744/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1840/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1903/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(608/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(160/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(513/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(608/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2128/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
EndFunc

Func DungeonEU_SnowmanAlert()
	_Send($MoveForwardDown)
	Sleep(15/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(705/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1631/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(240/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1856/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(544/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1616/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(784/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(592/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(672/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(448/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(1136/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
EndFunc

Func DungeonEU_HoarfrostHollow()
	_Send($MoveForwardDown)
	Sleep(1136/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(768/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(944/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(288/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1375/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1872/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(2064/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(480/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1072/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1616/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(192/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(640/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(672/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(720/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2208/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(607/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(784/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(656/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(800/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(1007/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2129/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1424/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1700/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
EndFunc

Func DungeonEU_BeginningOfTheMemory()
	_Send($MoveForwardDown)
	Sleep(3168/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2111/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(3760/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1200/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1488/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1808/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1840/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1680/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1423/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1569/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(8063/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(5136/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($BindNormal)
	Sleep(880/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1695/$SettingHostTimeScaleUse)
	_Send($BindSmall)
	Sleep(496/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(592/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1680/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1600/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(576/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(928/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(528/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1120/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(720/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2864/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(944/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(176/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(3343/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($BindNormal)
	Sleep(624/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse)
	_Send($BindSmall)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(240/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1664/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1871/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(832/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1216/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
EndFunc

Func DungeonEU_RuinsOfSanctityA()
	_Send($MoveForwardDown)
	Sleep(2207/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1472/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(288/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1712/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(352/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1503/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(688/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1232/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(2032/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(608/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(176/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1520/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1935/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(880/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(752/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(624/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(784/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1776/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1184/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(768/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1440/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1808/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
EndFunc

Func DungeonEU_GoldLeather()
	_Send($MoveForwardDown)
	Sleep(2192/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(1536/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(592/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(416/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1120/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(2655/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(4176/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1600/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(496/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1200/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(3103/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(704/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(3536/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1891/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1820/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc

Func DungeonEU_WindThroughTheRuins()
	_Send($MoveForwardDown)
	Sleep(3424/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(2288/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1375/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1936/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1120/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1840/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1680/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(736/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(752/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(576/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(864/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(4928/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1343/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(528/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2800/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(624/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(816/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1519/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1872/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1297/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(1855/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1696/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(944/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(400/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(800/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2256/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(480/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1328/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(576/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(576/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1855/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(752/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(2304/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(480/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(944/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1200/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(4591/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
EndFunc

Func DungeonEU_FrostStones()
	_Send($MoveLeftDown)
	Sleep(400/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1040/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1392/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(2992/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(2624/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(5151/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	_Send($MoveLeftUp)
EndFunc

Func DungeonEU_ATownEngulfed()
	_Send($MoveForwardDown)
	Sleep(592/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(256/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1232/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(192/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	SpamSkill(1, 0)
	Sleep(864/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(208/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(432/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(576/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(752/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1652/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1680/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1920/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(784/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(384/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1568/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1488/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(656/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(432/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2208/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1744/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1856/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2144/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1888/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1856/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(960/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1152/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1536/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(768/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(400/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1824/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1568/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1536/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1616/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1520/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(2448/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1808/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(864/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc

Func DungeonEU_HellBeyondTheDoor()
	_Send($MoveForwardDown)
	;Sleep(500)
	SpamSkill(1, 0)
	Sleep(828/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	_Send($MoveLeftDown)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1520/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1216/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(352/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(768/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(176/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(992/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(352/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(480/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(288/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(2880/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(880/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(176/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1232/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1136/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(160/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(704/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1232/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	SpamSkill(1, 0)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(400/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(816/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(352/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(1040/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(320/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1152/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(720/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(3488/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1008/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(1776/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	_Send($MoveBackwardDown)
	Sleep(560/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(736/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1872/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1712/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(480/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(144/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1008/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(208/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(816/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(640/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(592/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(352/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(688/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(704/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(272/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(432/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(672/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(480/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(800/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(896/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1120/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(800/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc
