Func Dungeon_Dungeon_TheFleeingGnollKingA()
	Send($MoveForwardDown)
	Sleep(2864 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1535 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2017 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2591 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightDown)
	Sleep(3472 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightUp)
	Sleep(2624 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightDown)
	Sleep(2911 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(688 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(336 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(624 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(592 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(512 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(528 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2080 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Sleep(16 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightUp)
	Sleep(256 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1888 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1568 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1872 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1536 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1599 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1521 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1536 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1807 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1584 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(3040 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightDown)
	Sleep(1743 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(1168 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(689 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(575 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Sleep(657 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(944 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(560 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(1024 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1135 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(560 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(160 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Sleep(1776 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(256 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(2688 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(1008 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(544 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1104 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightUp)
	Sleep(832 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightDown)
	Sleep(80 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Sleep(592 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1376 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(352 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(575 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1408 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1808 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1104 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(880 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveRightUp)
	Sleep(272 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1344 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(863 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveLeftDown)
	Sleep(305 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveLeftUp)
	Sleep(320 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1855 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1777 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1632 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1999 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1552 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1040 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveLeftDown)
	Sleep(544 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2016 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2448 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1823 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(1649 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(2911 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(2336 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Sleep(288 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(624 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(816 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardDown)
	Sleep(272 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveForwardUp)
	Sleep(304 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(704 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Sleep(2096 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardDown)
	Sleep(159 / $SettingHostTimeScaleUse * $SpeedMod)
	SpamSkill(1, 0)
	Sleep(2640 / $SettingHostTimeScaleUse * $SpeedMod)
	Send($MoveBackwardUp)
	Send($MoveLeftUp)
EndFunc   ;==>Dungeon_Dungeon_TheFleeingGnollKingA
