#include-once

Global $NA_PosY_ReturnToTown_6Party = 555
Global $NA_PosY_ReturnToTown_8Party = 555

Func DungeonNA_FrostStones()
	_Send($MoveForwardDown)
	_Send($MoveLeftDown)
	Sleep(2559/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(880/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(1888/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(2832/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(592/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(544/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(4752/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	_Send($MoveLeftUp)
EndFunc

Func DungeonNA_GoldLeather()
	_Send($MoveForwardDown)
	Sleep(3680/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(592/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(3567/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(576/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(3136/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1792/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(432/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(1072/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(400/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(12511/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(160/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1632/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1568/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(4127/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(4608/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1472/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2224/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc

Func DungeonNA_WindThroughTheRuins()
	_Send($MoveForwardDown)
	Sleep(3616/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(1648/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(432/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(1408/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1216/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1375/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1361/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1439/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(192/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(576/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(704/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(624/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2095/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(688/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1296/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(640/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(5712/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1776/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(3791/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(992/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(2304/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1936/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1039/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(6000/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(944/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(784/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(5104/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(383/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1104/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(928/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1056/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(208/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(6288/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1392/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(688/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(752/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(976/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(863/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1536/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
EndFunc

Func DungeonNA_ATownEngulfed()
	_Send($MoveForwardDown)
	Sleep(1152/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1216/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(976/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(896/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	_Send($MoveLeftDown)
	Sleep(896/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(672/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1232/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1408/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1216/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(768/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(736/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(896/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(544/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1008/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(720/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(880/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(912/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(592/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(480/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(896/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1008/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1920/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1632/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1632/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1584/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(5520/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(7488/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc

Func DungeonNA_HellBeyondTheDoor()
	_Send($MoveForwardDown)
	Sleep(1216/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(160/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1200/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1136/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(752/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(608/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1600/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(944/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1872/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1936/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(448/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(304/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1296/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(800/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(528/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(208/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(608/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(608/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1488/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1760/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1696/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1648/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1392/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(176/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(880/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1536/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1488/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(352/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(704/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(768/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1328/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(944/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(208/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(176/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(768/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2000/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2032/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(4976/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(144/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(2032/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(2112/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1408/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1376/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1152/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(448/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1616/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1904/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(192/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(448/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(368/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(2368/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1456/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1840/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(4400/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc

Func DungeonNA_FriendOrFoe()
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(496/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(368/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1040/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1168/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(848/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(480/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(3280/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(1136/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(560/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(464/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(3088/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(288/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(2848/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(112/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1168/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1264/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1184/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(928/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(960/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(992/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1104/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1232/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1056/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(752/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(800/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1184/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1840/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(2688/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(2672/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(416/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1824/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(3824/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(608/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(672/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1040/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1088/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(2832/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(1088/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(896/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(976/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1904/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(544/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(416/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(336/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1312/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(592/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1920/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1792/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(352/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(3552/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	_Send($MoveBackwardUp)
	Sleep(720/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	_Send($MoveLeftDown)
	Sleep(2256/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(1872/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(16/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1120/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1168/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1504/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1424/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1344/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(5552/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(4784/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
EndFunc

Func DungeonNA_EllissTrust()
	_Send($MoveRightDown)
	_Send($MoveForwardDown)
	Sleep(1072/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1712/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(2432/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(624/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(816/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	SpamSkill(1, 0)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(656/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(192/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(656/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(224/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(272/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(144/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(480/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(544/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(64/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(496/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(416/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(624/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(80/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(160/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(864/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1232/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1072/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1552/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(752/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1040/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(1504/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1840/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1680/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1024/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(720/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1008/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(432/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(32/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1200/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(416/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(848/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(192/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(512/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(352/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1696/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(976/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(736/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(576/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(656/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1088/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(208/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(80/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1568/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(2400/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(288/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(640/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(992/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(1136/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(160/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(768/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(3616/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(3456/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(384/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(480/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(688/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(560/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(255/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(449/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(224/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(816/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(528/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(368/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(304/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(496/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(48/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(464/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(288/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(160/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(896/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(320/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(720/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(432/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1376/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1248/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(832/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(720/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(1648/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(672/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(64/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(2256/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(96/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(4016/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(128/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(2752/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(112/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(2192/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(320/$SettingHostTimeScaleUse)
	_Send($BindSmall)
	Sleep(592/$SettingHostTimeScaleUse)
	_Send($BindNormal)
	Sleep(384/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1840/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(448/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(80/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(2016/$SettingHostTimeScaleUse)
	_Send($BindSmall)
	Sleep(848/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(1744/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(608/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(1280/$SettingHostTimeScaleUse)
	SpamSkill(1, 0)
	Sleep(1360/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(752/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(1440/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	Sleep(32/$SettingHostTimeScaleUse)
	_Send($MoveForwardUp)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveRightDown)
	Sleep(1184/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(1104/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(736/$SettingHostTimeScaleUse)
	_Send($MoveForwardDown)
	Sleep(3536/$SettingHostTimeScaleUse)
	_Send($MoveRightUp)
	_Send($MoveForwardUp)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(336/$SettingHostTimeScaleUse)
	_Send($MoveLeftDown)
	Sleep(288/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
	Sleep(256/$SettingHostTimeScaleUse)
	_Send($MoveBackwardDown)
	Sleep(80/$SettingHostTimeScaleUse)
	_Send($MoveLeftUp)
	Sleep(7568/$SettingHostTimeScaleUse)
	_Send($MoveBackwardUp)
EndFunc
