#Region ;**** Directives created by AutoIt3Wrapper_GUI ****
#AutoIt3Wrapper_Outfile=bin\setbinds.exe
#EndRegion ;**** Directives created by AutoIt3Wrapper_GUI ****
AutoItSetOption("SendKeyDownDelay", 0)
WinActivate("[Class:ConsoleWindowClass]")
Send("bind ""KP_END"" ""cc_fill_all_items""" & @CRLF)
Send("bind ""KP_DOWNARROW"" ""incrementvar plr_turning_movement_speed_rate_min 1 6 5""" & @CRLF)
Send("bind ""KP_PGDN"" ""changemap_to_current_random_sector""" & @CRLF)
Send("bind ""KP_LEFTARROW"" ""cc_change_figure_height 0.1""" & @CRLF)
Send("bind ""KP_5"" ""cc_change_figure_height 1""" & @CRLF)
Send("bind ""KP_RIGHTARROW"" ""changemap_to_next_random_sector""" & @CRLF)
Send("bind ""KP_HOME"" ""cc_set_sub_weapon javelin_lvl2 999""" & @CRLF)
Send("bind ""KP_UPARROW"" ""cc_set_sub_weapon handbomb_lvl2 999""" & @CRLF)
Send("bind ""KP_PGUP"" ""cc_set_sub_weapon mining_bomb 999""" & @CRLF)
Send("bind ""KP_INS"" ""god""" & @CRLF)
Send("bind ""KP_MINUS"" ""ohk""" & @CRLF)
Send("bind ""KP_PLUS"" ""cc_set_sub_weapon sticky_bomb 999""" & @CRLF)
Send("bind ""KP_SLASH"" ""incrementvar host_timescale 1 5 4""" & @CRLF)
Send("bind ""KP_DEL"" ""blacksmith_craft_time_sec 0.25""" & @CRLF)
Send("bind ""UPARROW"" ""plr_play_overlay_sequence paladin_transformation_begin_1""" & @CRLF)
Send("bind ""DOWNARROW"" ""plr_play_overlay_sequence dark_knight_transformation_begin_1""" & @CRLF)
Send("bind ""RIGHTARROW"" ""plr_play_overlay_sequence paladin_transformation_begin_2""" & @CRLF)
Send("bind ""LEFTARROW"" ""plr_play_overlay_sequence dark_knight_transformation_begin_2""" & @CRLF)
Send("bind ""PGUP"" ""plr_play_overlay_sequence paladin_2_skill_tentacle""" & @CRLF)
Send("bind ""PGDN"" ""plr_play_overlay_sequence dark_knight_2_skill_tentacle""" & @CRLF)
Send("bind ""]"" ""incrementvar plr_search_evil_core_distance 500 1700 400""" & @CRLF)
Send("bind ""p"" ""plr_search_evil_core_distance 100""" & @CRLF)
Send("bind ""o"" ""ohk2""" & @CRLF)
Send("bind ""["" ""cc_change_figure_height 1500""" & @CRLF)
Send("bind ""="" ""cc_shiplist_ui""" & @CRLF)
Send("bind ""-"" ""cc_send_start_game_message""" & @CRLF)
Send("bind ""l"" ""cc_change_start_game_message""" & @CRLF)
Send("bind "","" ""cc_enter_colhen_from_rochest""" & @CRLF)
Send("bind ""."" ""cc_enter_rochest_from_colhen""" & @CRLF)
Send("bind ""/"" ""sk_plr_lethita_stamina_fast_restoration_time_condition -1""" & @CRLF)
Send("bind ""*"" ""cc_breakownarmor""" & @CRLF)
WinActivate("[Class:Valve001]")
MouseClick("left", 1640, 63, 1, 5)
Send("denboice@gmail.com")
Send("{TAB}")
Send("lovers4life")
MouseClick("left, 816, 630, 1, 5)
Do
	Sleep(100)
Until PixelGetColor(1640, 63) == 0
MouseClick("left", 1758, 61, 1, 5)
Sleep(3000)
MouseClick("left", 954, 1027, 1, 5)
